[tool.poetry]
name = "flatmapknowledge"
version = "1.9.3"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
mapknowledge = {url = "https://github.com/AnatomicMaps/map-knowledge/releases/download/v0.19.3/mapknowledge-0.19.3-py3-none-any.whl"}
