[tool.poetry]
name = "flatmapknowledge"
version = "1.0.4"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
mapknowledge = {url = "https://github.com/AnatomicMaps/map-knowledge/releases/download/v0.10.7/mapknowledge-0.10.7-py3-none-any.whl"}
