[tool.poetry]
name = "flatmapknowledge"
version = "1.9.1"
description = ""
authors = ["David Brooks <d.brooks@auckland.ac.nz>"]

[tool.poetry.dependencies]
mapknowledge = {url = "https://github.com/AnatomicMaps/map-knowledge/releases/download/v0.19.1/mapknowledge-0.19.1-py3-none-any.whl"}
python = ">=3.12,<4.0"
